import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { EcosystemPageShell } from "@/src/components/ecosystem/EcosystemPageShell";
import { type Locale } from "@/src/config/site";
import { agents } from "@/src/data/ai-universe";
import { getLocale } from "@/src/lib/i18n";
export async function generateStaticParams() { return agents.flatMap((agent) => ["en", "zh", "ja"].map((locale) => ({ locale, id: agent.id }))); }
export async function generateMetadata({ params }: { params: Promise<{ id: string }> }): Promise<Metadata> { const { id } = await params; const agent = agents.find((item) => item.id === id); return { title: agent ? `${agent.name} Agent` : "Agent", description: agent?.description ?? "AI agent detail." }; }
export default async function AgentDetailPage({ params }: { params: Promise<{ locale: string; id: string }> }) { const { locale: rawLocale, id } = await params; const locale: Locale = getLocale(rawLocale); const agent = agents.find((item) => item.id === id); if (!agent) notFound(); return <EcosystemPageShell locale={locale} eyebrow={agent.category} title={agent.name} subtitle={agent.description}><div className="grid gap-6 lg:grid-cols-[1.5fr_1fr]"><section className="rounded-3xl border border-white/15 bg-white/10 p-6 backdrop-blur-xl"><h2 className="text-2xl font-black">Prompt blueprint</h2><p className="mt-4 rounded-2xl bg-slate-950/50 p-5 leading-8 text-cyan-100">{agent.prompt}</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><p className="rounded-2xl bg-white/10 p-4"><b>Rating</b><br />★ {agent.rating}</p><p className="rounded-2xl bg-white/10 p-4"><b>Downloads</b><br />{agent.downloads.toLocaleString()}</p><p className="rounded-2xl bg-white/10 p-4"><b>Created</b><br />{agent.createdAt}</p></div></section><aside className="rounded-3xl border border-white/15 bg-white/10 p-6 backdrop-blur-xl"><h2 className="text-2xl font-black">Creator</h2><p className="mt-4 text-xl font-bold text-cyan-200">{agent.creatorName}</p><p className="mt-3 text-slate-200">{agent.creatorBio}</p><p className="mt-5 text-sm font-bold text-slate-300">Creator ID: {agent.creatorId}</p></aside></div></EcosystemPageShell>; }
