"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { ArrowLeft, LoaderCircle, Sparkles } from "lucide-react";
import { SmartImage } from "@/src/components/SmartImage";

const types = [{ id: "article", label: "文章 / Article" }, { id: "travel plan", label: "旅行计划 / Travel plan" }, { id: "learning roadmap", label: "学习路线 / Learning roadmap" }, { id: "product introduction", label: "产品介绍 / Product intro" }];
type Creation = { title: string; content: string; seoDescription: string; image: { keyword: string } };

export default function CreatePage() {
  const [type, setType] = useState(types[0].id); const [prompt, setPrompt] = useState(""); const [result, setResult] = useState<Creation | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function create(event: FormEvent) { event.preventDefault(); if (!prompt.trim()) return; setLoading(true); setError(""); try { const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ prompt, type }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || "Generation failed"); setResult(body.data); } catch (cause) { setError(cause instanceof Error ? cause.message : "Generation failed"); } finally { setLoading(false); } }
  return <main className="animated-gradient min-h-screen bg-slate-950 px-6 py-12 text-white"><div className="mx-auto max-w-6xl"><Link href="/en" className="inline-flex items-center gap-2 text-sm font-bold text-slate-300"><ArrowLeft size={16} /> Back home</Link><div className="mt-10 grid gap-8 lg:grid-cols-[.75fr_1.25fr]"><form onSubmit={create} className="glass-card h-fit rounded-[2rem] p-7"><p className="text-xs font-black uppercase tracking-[.25em] text-violet-300">AI Creation Center</p><h1 className="mt-3 text-4xl font-black">Create your next idea.</h1><fieldset className="mt-7 grid grid-cols-2 gap-2"><legend className="sr-only">Content type</legend>{types.map((item) => <button type="button" key={item.id} onClick={() => setType(item.id)} className={`rounded-xl border p-3 text-sm font-bold ${type === item.id ? "border-violet-300 bg-violet-500/30" : "border-white/10 bg-white/5"}`}>{item.label}</button>)}</fieldset><label htmlFor="creation-prompt" className="mt-6 block text-sm font-bold">Describe your goal</label><textarea id="creation-prompt" value={prompt} onChange={(event) => setPrompt(event.target.value)} required maxLength={1000} rows={7} className="mt-2 w-full resize-none rounded-2xl border border-white/15 bg-slate-950/50 p-4 outline-none focus:ring-2 focus:ring-violet-400" placeholder="Audience, goals, tone, places, or topics…" /><button disabled={loading} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-violet-500 to-cyan-400 py-4 font-black disabled:opacity-50">{loading ? <LoaderCircle className="animate-spin" /> : <Sparkles />} Generate</button>{error && <p role="alert" className="mt-4 text-rose-300">{error}</p>}</form><section className="glass-card min-h-[34rem] overflow-hidden rounded-[2rem]">{result ? <><SmartImage content={`${type} ${prompt} ${result.image.keyword}`} className="h-64" priority /><div className="p-7"><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-300">Generated {type}</p><h2 className="mt-3 text-3xl font-black">{result.title}</h2><p className="mt-5 whitespace-pre-line leading-8 text-slate-200">{result.content}</p><div className="mt-7 rounded-2xl bg-white/5 p-4"><p className="text-xs font-black uppercase tracking-wider text-violet-300">SEO description</p><p className="mt-2 text-sm text-slate-300">{result.seoDescription}</p></div></div></> : <div className="flex min-h-[34rem] items-center justify-center p-10 text-center text-slate-400"><div><Sparkles className="mx-auto mb-4" size={40} /><p>Your generated title, content, SEO description, and matched image will appear here.</p></div></div>}</section></div></div></main>;
}
