import type { Topic } from "@/src/data/grade9";
import type { Locale } from "@/src/config/site";
import { localize } from "@/src/lib/grade9-curriculum";
import { LearningProgress } from "./LearningProgress";
import { QuickCheck } from "./QuickCheck";

export function CompleteLesson({ topic, locale }: { topic: Topic; locale: Locale }) {
  return <article className="min-w-0 space-y-10 text-[1.05rem] leading-8 text-slate-200">
    <header><h1 className="text-3xl font-black leading-tight text-white sm:text-5xl">{localize(topic.title, locale)}</h1><div className="mt-6 border-l-4 border-cyan-300 bg-cyan-950/30 px-5 py-4"><h2 className="font-bold text-cyan-200">学完你将能够……</h2><p>{localize(topic.learningObjective, locale)}</p></div></header>
    <section aria-labelledby="prerequisites"><h2 id="prerequisites" className="text-2xl font-bold text-white">前置知识</h2><ul className="mt-3 list-disc pl-6">{topic.prerequisites.map((item) => <li key={item.zh}>{localize(item, locale)}</li>)}</ul></section>
    <section aria-labelledby="introduction"><h2 id="introduction" className="text-2xl font-bold text-white">知识点导入</h2><p className="mt-3">{localize(topic.introduction, locale)}</p></section>
    <nav aria-label="页面内目录" className="rounded-2xl border border-white/10 bg-slate-900/70 p-5"><h2 className="font-bold text-white">本课目录</h2><ol className="mt-2 list-decimal pl-6">{topic.sections.map((section) => <li key={section.id}><a className="text-cyan-300 underline-offset-4 hover:underline focus-visible:outline focus-visible:outline-2" href={`#${section.id}`}>{localize(section.title, locale)}</a></li>)}</ol></nav>
    {topic.sections.map((section, index) => <section id={section.id} key={section.id} className="scroll-mt-8"><p className="text-sm font-bold text-cyan-300">{String(index + 1).padStart(2, "0")}</p><h2 className="mt-1 text-2xl font-bold text-white">{localize(section.title, locale)}</h2><div className="mt-4 space-y-4">{section.paragraphs.map((paragraph, paragraphIndex) => <p key={paragraphIndex}>{localize(paragraph, locale)}</p>)}</div>{section.bullets && <ul className="mt-4 list-disc pl-6">{section.bullets.map((item) => <li key={item.zh}>{localize(item, locale)}</li>)}</ul>}{section.formula && <div className="mt-5 overflow-x-auto rounded-xl bg-slate-900 p-4 font-mono" aria-label="公式">{section.formula}</div>}</section>)}
    {topic.formula && <section><h2 className="text-2xl font-bold text-white">公式或重要结论</h2><div className="mt-4 overflow-x-auto rounded-xl border border-cyan-300/20 bg-slate-900 p-5 font-mono text-xl" aria-label="公式">{topic.formula}</div></section>}
    <section><h2 className="text-2xl font-bold text-white">解题方法</h2><ol className="mt-4 space-y-3">{topic.methodSteps.map((step, index) => <li className="flex gap-3" key={step.zh}><span className="font-bold text-cyan-300">{index + 1}.</span><span>{localize(step, locale)}</span></li>)}</ol></section>
    <section><h2 className="text-2xl font-bold text-white">典型例题与逐步解答</h2>{topic.workedExamples.map((example) => <div className="mt-5 rounded-2xl bg-slate-900 p-5 sm:p-7" key={example.title.zh}><h3 className="text-xl font-bold text-cyan-200">{localize(example.title, locale)}</h3><p className="mt-4"><strong className="text-white">题目：</strong>{localize(example.problem, locale)}</p><h4 className="mt-5 font-bold text-white">解答步骤</h4><ol className="mt-2 space-y-3">{example.steps.map((step, index) => <li className="flex gap-3" key={index}><span className="shrink-0 rounded-full bg-cyan-950 px-2 text-cyan-200">{index + 1}</span><span>{localize(step, locale)}</span></li>)}</ol><p className="mt-5"><strong className="text-emerald-300">答案：</strong>{localize(example.answer, locale)}</p><p className="mt-3 text-slate-300"><strong className="text-white">为什么这样做：</strong>{localize(example.explanation, locale)}</p></div>)}</section>
    <section><h2 className="text-2xl font-bold text-white">常见错误与修正</h2><div className="mt-4 grid gap-4">{topic.commonMistakes.map((item, index) => <div className="rounded-2xl border border-rose-300/20 bg-rose-950/20 p-5" key={index}><h3 className="font-bold text-rose-200">错误表现：{localize(item.mistake, locale)}</h3><p className="mt-2"><strong>为什么错：</strong>{localize(item.whyWrong, locale)}</p><p className="mt-2"><strong>正确做法：</strong>{localize(item.correction, locale)}</p></div>)}</div></section>
    <QuickCheck topic={topic} locale={locale} />
    <LearningProgress topicId={topic.id} />
  </article>;
}
