"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { subjects } from "@/src/data/grade9";
import { localize } from "@/src/lib/grade9-curriculum";
import type { Locale } from "@/src/config/site";
import { calculateStudyStreak, createEmptyProgress, getDueTopics, getSubjectProgress, getWeakTopics, PROGRESS_EVENT, readLearningProgress, type LearningProgressV23 } from "@/src/lib/learning-progress";

const labels = { zh: { title: "学习仪表盘", overall: "总体掌握度", learned: "已学习", due: "今日待复习", streak: "连续学习", days: "天", subjects: "七科进度", resume: "继续上次学习", review: "今日复习", weak: "薄弱知识点", recent: "最近学习", empty: "还没有学习记录。从任意知识点开始，进度会自动保存在本浏览器。", start: "开始学习", loading: "正在读取本地学习进度…" }, en: { title: "Learning dashboard", overall: "Overall mastery", learned: "Topics learned", due: "Due today", streak: "Study streak", days: "days", subjects: "Seven subjects", resume: "Continue learning", review: "Today's review", weak: "Weak topics", recent: "Recent learning", empty: "No learning history yet. Start a topic and progress will be saved in this browser.", start: "Start learning", loading: "Loading local progress…" }, ja: { title: "学習ダッシュボード", overall: "総合習熟度", learned: "学習済み", due: "今日の復習", streak: "連続学習", days: "日", subjects: "7教科の進捗", resume: "前回の続き", review: "今日の復習", weak: "苦手な知識点", recent: "最近の学習", empty: "学習記録はまだありません。知識点を開くと、このブラウザに保存されます。", start: "学習を始める", loading: "ローカル進捗を読み込み中…" } };
export function ProgressDashboard({ locale }: { locale: Locale }) {
  const [mounted, setMounted] = useState(false); const [progress, setProgress] = useState<LearningProgressV23>(createEmptyProgress()); const content = labels[locale];
  useEffect(() => { const refresh = () => setProgress(readLearningProgress()); refresh(); setMounted(true); window.addEventListener(PROGRESS_EVENT, refresh); window.addEventListener("storage", refresh); return () => { window.removeEventListener(PROGRESS_EVENT, refresh); window.removeEventListener("storage", refresh); }; }, []);
  const topicMap = useMemo(() => new Map(subjects.flatMap((subject) => subject.chapters.flatMap((chapter) => chapter.topics.map((topic) => [topic.id, { topic, subject }] as const)))), []);
  if (!mounted) return <p role="status" className="rounded-2xl bg-slate-900 p-6">{content.loading}</p>;
  const total = subjects.flatMap((subject) => subject.chapters.flatMap((chapter) => chapter.topics)).length; const values = Object.values(progress.topics); const learned = values.filter((topic) => topic.learnedAt).length; const overall = total ? Math.round(values.reduce((sum, topic) => sum + topic.mastery, 0) / total) : 0; const due = getDueTopics(progress); const weak = getWeakTopics(progress); const resolve = (id: string) => { const entry = topicMap.get(id); return entry ? { title: localize(entry.topic.title, locale), href: `/${locale}/knowledge/grade-9/${entry.subject.slug}/${entry.topic.slug}` } : undefined; }; const recent = progress.recentTopicIds.map(resolve).filter(Boolean) as Array<{ title: string; href: string }>;
  if (!recent.length) return <section className="rounded-3xl border border-cyan-300/20 bg-slate-900 p-8 text-center"><h1 className="text-3xl font-black">{content.title}</h1><p className="mx-auto mt-4 max-w-xl text-slate-300">{content.empty}</p><Link href={`/${locale}/knowledge/grade-9`} className="mt-6 inline-block rounded-xl bg-cyan-300 px-5 py-3 font-bold text-slate-950">{content.start}</Link></section>;
  const topicList = (title: string, ids: string[]) => <section className="rounded-2xl bg-slate-900 p-5"><h2 className="text-xl font-bold">{title}</h2>{ids.length ? <ul className="mt-3 space-y-2">{ids.map(resolve).filter(Boolean).map((item) => item && <li key={item.href}><Link className="block rounded-lg bg-slate-950 p-3 focus-visible:outline focus-visible:outline-2 focus-visible:outline-cyan-300" href={item.href}>{item.title} →</Link></li>)}</ul> : <p className="mt-3 text-slate-400">—</p>}</section>;
  return <><h1 className="text-4xl font-black">{content.title}</h1><section className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{[[content.overall, `${overall}%`], [content.learned, `${learned} / ${total}`], [content.due, String(due.length)], [content.streak, `${calculateStudyStreak(progress.studyDates)} ${content.days}`]].map(([label, value]) => <article key={label} className="rounded-2xl bg-slate-900 p-5"><p className="text-sm text-slate-400">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></article>)}</section><section className="mt-6 rounded-2xl bg-slate-900 p-5"><h2 className="text-xl font-bold">{content.subjects}</h2><div className="mt-4 space-y-4">{subjects.map((subject) => { const stat = getSubjectProgress(progress, subject.chapters.flatMap((chapter) => chapter.topics.map((topic) => topic.id))); return <div key={subject.id}><div className="flex justify-between text-sm"><span>{subject.icon} {localize(subject.name, locale)}</span><span>{stat.mastery}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-700" role="progressbar" aria-valuenow={stat.mastery} aria-valuemin={0} aria-valuemax={100}><div className="h-full rounded-full bg-cyan-300 motion-reduce:transition-none" style={{ width: `${stat.mastery}%` }}/></div></div>; })}</div></section><Link href={recent[0].href} className="mt-6 block rounded-2xl bg-cyan-300 p-5 font-bold text-slate-950">{content.resume}：{recent[0].title} →</Link><div className="mt-6 grid gap-5 lg:grid-cols-3">{topicList(content.review, due.map((topic) => topic.topicId))}{topicList(content.weak, weak.map((topic) => topic.topicId))}{topicList(content.recent, progress.recentTopicIds)}</div></>;
}
